close all;
clear;
clc;
addpath(genpath('l1'));

%% 载入数据
m_img = 112;                                                               %图像尺寸调整为m_img*n_img
n_img = 92;
Train_num = 8;                                                             %每个对象选取8张图片组成训练集
Test_num = 2;                                                              %每个对象剩余2张图片组成测试集

%载入训练集到V，样本分类号到class_V,载入测试集到T,样本分类号到class_T
V = zeros(m_img * n_img , 40 * Train_num);                                 %原始数据矩阵,每一列为一张图片
class_V = zeros(40 * Train_num, 1);
T = zeros(m_img * n_img , 40 * Test_num);    
class_T = zeros(40 * Test_num, 1);
for i = 1 : 40
    currPath = ['.\data\s', num2str(i)];
    Files = dir(fullfile(currPath, '*.*'));
    LengthFiles = length(Files);
    rN = randperm(10);                                                     %随机划分训练集和测试集
    for j = 1 : Train_num
        img_path = [currPath ,'\' , Files(rN(j) + 2).name];
        img = imread(img_path);
        img = imresize(img, [m_img n_img]);
        img_vector = img(1 : m_img * n_img);                               %图片向量化，作为初始数据矩阵中的一个列
        V(:,j + (i - 1) * Train_num) = double(img_vector);                 %存储图片
        class_V(j + (i - 1) * Train_num) = i;                              %存储类别信息
    end
    for j = 1 : Test_num
        img_path = [currPath ,'\' , Files(rN(j + Train_num) + 2).name];
        img = imread(img_path);
        img = imresize(img, [m_img n_img]);
        img_vector = img(1 : m_img * n_img);                               %图片向量化，作为初始数据矩阵中的一个列
        T(:,j + (i - 1) * Test_num) = double(img_vector);                  %存储图片
        class_T(j + (i - 1) * Test_num) = i;                               %存储类别信息
    end
end
% t1 = clock;
% rc_PCA_0 = PCA(m_img, n_img, V, class_V, Train_num, T, class_T, Test_num, T);
% t2 = clock;
% time_PCA_0 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_0 = imp_PCA(m_img, n_img, V, class_V, Train_num, T, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_0 = etime(t2,t1);
% t1 = clock;
% rc_NMF_0 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T, class_T, Test_num, T);
% t2 = clock;
% time_NMF_0 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_0 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_0 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_0 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_0 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_0 = PCA_SRC( V, class_V, Train_num, T, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_0 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_0 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_0 = etime(t2,t1);

%% 构造遮挡图像集
T_9 = zeros(m_img * n_img , 40 * Test_num);
T_25 = zeros(m_img * n_img , 40 * Test_num);
T_49 = zeros(m_img * n_img , 40 * Test_num);
for j = 1 : Test_num * 40
    img = T(:,j);
    img = reshape(img, m_img, n_img); 
    m_9 = randperm(79);
    n_9 = randperm(65);
    img(m_9 : m_9 + 33, n_9 : n_9 + 27) = 1;
    T_9(:, j) = double(img(1 : m_img * n_img));
    
    img = T(:,j);
    img = reshape(img, m_img, n_img);
    m_25 = randperm(57);
    n_25 = randperm(47);
    img(m_25 : m_25 + 55, n_25 : n_25 + 45) = 1;
    T_25(:, j) = double(img(1 : m_img * n_img));
    
    img = T(:,j);
    img = reshape(img, m_img, n_img);
    m_49 = randperm(35);
    n_49 = randperm(29);
    img(m_49 : m_49 + 77, n_49 : n_49 + 63) = 1;
    T_49(:, j) = double(img(1 : m_img * n_img));                               %存储类别信息
end
% t1 = clock;
% rc_PCA_9 = PCA(m_img, n_img, V, class_V, Train_num, T_9, class_T, Test_num, T);
% t2 = clock;
% time_PCA_9 = etime(t2,t1);
% t1 = clock;
% rc_PCA_25 = PCA(m_img, n_img, V, class_V, Train_num, T_25, class_T, Test_num, T);
% t2 = clock;
% time_PCA_25 = etime(t2,t1);
% t1 = clock;
% rc_PCA_49 = PCA(m_img, n_img, V, class_V, Train_num, T_49, class_T, Test_num, T);
% t2 = clock;
% time_PCA_49 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_9 = imp_PCA(m_img, n_img, V, class_V, Train_num, T_9, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_9 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_25 = imp_PCA(m_img, n_img, V, class_V, Train_num, T_25, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_25 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_49 = imp_PCA(m_img, n_img, V, class_V, Train_num, T_49, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_49 = etime(t2,t1);
% t1 = clock;
% rc_NMF_9 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T_9, class_T, Test_num, T);
% t2 = clock;
% time_NMF_9 = etime(t2,t1);
% t1 = clock;
% rc_NMF_25 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T_25, class_T, Test_num, T);
% t2 = clock;
% time_NMF_25 = etime(t2,t1);
% t1 = clock;
% rc_NMF_49 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T_49, class_T, Test_num, T);
% t2 = clock;
% time_NMF_49 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_9 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_9, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_9 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_25 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_25, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_25 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_49 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_49, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_49 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_9 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_9, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_9 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_25 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_25, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_25 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_49 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_49, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_49 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_9 = PCA_SRC( V, class_V, Train_num, T_9, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_9 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_25 = PCA_SRC( V, class_V, Train_num, T_25, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_25 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_49 = PCA_SRC( V, class_V, Train_num, T_49, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_49 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_9 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T_9, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_9 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_25 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T_25, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_25 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_49 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T_49, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_49 = etime(t2,t1);

%% 构造带噪图像集
T_n30 = zeros(m_img * n_img , 40 * Test_num);
T_n60 = zeros(m_img * n_img , 40 * Test_num);
T_n90 = zeros(m_img * n_img , 40 * Test_num);
for j = 1 : Test_num * 40
    img = T(:,j);
    noise_30 = round(rand(1, 33 * 27)) * 254 + 1;
    rN = randperm(m_img * n_img);
    rN = rN(1 : 33 * 27)';
    for i = 1 : 33 * 27
        img(rN(i)) = noise_30(i);
    end    
    T_n30(:, j) = img;
    
    img = T(:,j);
    noise_60 = round(rand(1, 66 * 54)) * 254 + 1;
    rN = randperm(m_img * n_img);
    rN = rN(1 : 66 * 54)';
    for i = 1 : 66 * 54
        img(rN(i)) = noise_60(i);
    end
    T_n60(:, j) = img;
    
    img = T(:,j);
    noise_90 = round(rand(1, 99 * 81)) * 254 + 1;
    rN = randperm(m_img * n_img);
    rN = rN(1 : 99 * 81)';
    for i = 1 : 99 * 81
        img(rN(i)) = noise_90(i);
    end
    T_n90(:, j) = img;
end
% t1 = clock;
% rc_PCA_n30 = PCA(m_img, n_img, V, class_V, Train_num, T_n30, class_T, Test_num, T);
% t2 = clock;
% time_PCA_n30 = etime(t2,t1);
% t1 = clock;
% rc_PCA_n60 = PCA(m_img, n_img, V, class_V, Train_num, T_n60, class_T, Test_num, T);
% t2 = clock;
% time_PCA_n60 = etime(t2,t1);
% t1 = clock;
% rc_PCA_n90 = PCA(m_img, n_img, V, class_V, Train_num, T_n90, class_T, Test_num, T);
% t2 = clock;
% time_PCA_n90 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_n30 = imp_PCA(m_img, n_img, V, class_V, Train_num, T_n30, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_n30 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_n60 = imp_PCA(m_img, n_img, V, class_V, Train_num, T_n60, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_n60 = etime(t2,t1);
% t1 = clock;
% rc_imp_PCA_n90 = imp_PCA(m_img, n_img, V, class_V, Train_num, T_n90, class_T, Test_num, T);
% t2 = clock;
% time_imp_PCA_n90 = etime(t2,t1);
% t1 = clock;
% rc_NMF_n30 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T_n30, class_T, Test_num, T);
% t2 = clock;
% time_NMF_n30 = etime(t2,t1);
% t1 = clock;
% rc_NMF_n60 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T_n60, class_T, Test_num, T);
% t2 = clock;
% time_NMF_n60 = etime(t2,t1);
% t1 = clock;
% rc_NMF_n90 = NMF_mse(V, class_V, m_img, n_img, Train_num, 128, 1000, T_n90, class_T, Test_num, T);
% t2 = clock;
% time_NMF_n90 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_n30 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_n30, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_n30 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_n60 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_n60, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_n60 = etime(t2,t1);
% t1 = clock;
% rc_LNMF_n90 = LNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_n90, class_T, Test_num, T);
% t2 = clock;
% time_LNMF_n90 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_n30 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_n30, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_n30 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_n60 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_n60, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_n60 = etime(t2,t1);
% t1 = clock;
% rc_FNMF_n90 = FNMF(V, class_V, m_img, n_img, 1, 1, Train_num, 128, 10000, T_n90, class_T, Test_num, T);
% t2 = clock;
% time_FNMF_n90 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_n30 = PCA_SRC( V, class_V, Train_num, T_n30, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_n30 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_n60 = PCA_SRC( V, class_V, Train_num, T_n60, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_n60 = etime(t2,t1);
% t1 = clock;
% rc_PCA_SRC_n90 = PCA_SRC( V, class_V, Train_num, T_n90, class_T, Test_num);
% t2 = clock;
% time_PCA_SRC_n90 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_n30 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T_n30, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_n30 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_n60 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T_n60, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_n60 = etime(t2,t1);
% t1 = clock;
% rc_randomface_SRC_n90 = randomface_SRC(m_img, n_img, V, class_V, Train_num, T_n90, class_T, Test_num);
% t2 = clock;
% time_randomface_SRC_n90 = etime(t2,t1);

% t1 = clock;
% rc_SRC_0 = SRC(m_img, n_img, V, class_V, Train_num, T, class_T, Test_num);
% t2 = clock;
% time_SRC_0 = etime(t2,t1);
t1 = clock;
rc_SRC_9 = SRC(m_img, n_img, V, class_V, Train_num, T_9, class_T, Test_num);
t2 = clock;
time_SRC_9 = etime(t2,t1);
t1 = clock;
rc_SRC_25 = SRC(m_img, n_img, V, class_V, Train_num, T_25, class_T, Test_num);
t2 = clock;
time_SRC_25 = etime(t2,t1);
t1 = clock;
rc_SRC_49 = SRC(m_img, n_img, V, class_V, Train_num, T_49, class_T, Test_num);
t2 = clock;
time_SRC_49 = etime(t2,t1);
% t1 = clock;
% rc_SRC_n30 = SRC(m_img, n_img, V, class_V, Train_num, T_n30, class_T, Test_num);
% t2 = clock;
% time_SRC_n30 = etime(t2,t1);
% t1 = clock;
% rc_SRC_n60 = SRC(m_img, n_img, V, class_V, Train_num, T_n60, class_T, Test_num);
% t2 = clock;
% time_SRC_n60 = etime(t2,t1);
% t1 = clock;
% rc_SRC_n90 = SRC(m_img, n_img, V, class_V, Train_num, T_n90, class_T, Test_num);
% t2 = clock;
% time_SRC_n90 = etime(t2,t1);